name: Test with astro check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test-astro-check:
    name: Basic check with astro check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run astro check 
        run: npm run check
