name: Test with `astro check` 

on:
  workflow_call:

permissions:
  contents: read

env:
  BUILD_PATH: "."
  # BUILD_PATH: subfolder

jobs:
  test-astro-check:
    name: Check with `astro check` 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}
      - name: Check with astro check
        run: |
          npm run check
        working-directory: ${{ env.BUILD_PATH }}

